---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: production
  labels:
    app: hello
  annotations:
    fluxcd.io/automated: 'true'
spec:
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: vishnu4772/demo-gitops:hellov2.0
